include: package:effective_dart/analysis_options.yaml
linter:
  rules:
    unnecessary_const: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    public_member_api_docs: false
    prefer_relative_imports: false    
analyzer:
  enable-experiment:
    - non-nullable
  errors:
    missing_required_param: warning
    missing_return: warning
    todo: ignore
    sdk_version_async_exported_from_core: ignore
  exclude:
    - 'bin/cache/**'
    - 'lib/i18n/stock_messages_*.dart'
    - 'lib/src/http/**'
    - 'test/**'
