name: fl_chart
description: A powerful Flutter chart library, currently supporting Line Chart, Bar Chart and Pie Chart.
version: 0.36.1
homepage: https://github.com/imaNNeoFighT/fl_chart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.0
  effective_dart: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
