name: fl_chart
description: A powerful Flutter chart library, currently supporting Line Chart, Bar Chart and Pie Chart.
version: 0.36.1
homepage: https://github.com/imaNNeoFighT/fl_chart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.3
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
  
